### ISSUE TITLE
Mock Tests

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-auth-facebook#10]
do you need help with mocking the FB endpoints?

**Comment by jackcarlisle** [comment]
@nelsonic I was looking at it last night and I wrote a mock test this morning but I'm not sure if it's the right way of doing it. The test does pass but I was wondering if you could take a look. I've pushed it up to a branch called 'mockTest'.

**Comment by nelsonic** [comment]
@jackcarlisle looks fine. 
Does FB have a "repo" scope tho? 
https://github.com/dwyl/hapi-auth-facebook/blob/6f4e161ec171af546e1edeafc318f1cceb72d3e4/test/facebook.test.js#L24 :wink:

**Comment by jackcarlisle** [comment]
@nelsonic I copied your github access token example just to see if the test would pass. I'll replace it with the accurate fb data, which I think is ![access_data](https://files.gitter.im/jackcarlisle/hapi-auth-facebook/FgBH/thumb/Screen-Shot-2015-11-28-at-10.24.57.png)?

**Comment by jackcarlisle** [comment]
Sorry here's a better picture ![access](https://files.gitter.im/jackcarlisle/hapi-auth-facebook/FgBH/Screen-Shot-2015-11-28-at-10.24.57.png)

**Comment by nelsonic** [comment]
*almost* ... do the tests still pass with that fixture?

**Comment by jackcarlisle** [comment]
yeah it still passes the test. I think I'm only checking that I'm getting a response, not that I'm getting a specific access token. I'm still a bit confused about mock testing

**Comment by nelsonic** [comment]
If you are *confused* its because we (*I*) did a *terrible* job of explaining it ... :disappointed: 
Let's fix that.

**Comment by jackcarlisle** [comment]
Sounds good! I think your explanation was good, it's just my testing in general is out of practice but working through an example has definitely helped my understanding. You mentioned a good [repo](https://github.com/pgte/nock) yesterday by Pedro Teixeira which I'll check out over the weekend.

**Comment by jackcarlisle** [comment]
@nelsonic I managed to get the right response format in the end: 
```javascript
var mockToken = {
  "access_token": "abcdefghijklmnopqrstuvwxyzDUMMY_TOKEN1234567890",
  "token_type": "bearer",
  "expires_in": 5183971
};
```
