### ISSUE TITLE
External API Request.

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/hapi-auth-facebook#11]
Hi @nelsonic , sorry to ask you a question in the weekend, but we are trying to find the most efficient way of making an extrenal api request. This is the way we have been doing it in the past prior to hapi - https://github.com/dwyl/hapi-auth-facebook/blob/master/lib/index.js#L40-L51

Is this the best way to do it in hapi too? or is there another built in method that will let us do something similar to this?

**Comment by nelsonic** [comment]
Hi @sohilpandya,
sorry I only saw this now. You're always fine to ask questions in GitHub issues. :+1:  

We have *several* options when making http requests to APIs:

+ use node's http/https module and write your own `https.request` (usually takes [about 10 lines of code](https://github.com/dwyl/hapi-auth-facebook/blob/f971b8ef0abc8a6d547671c738698dffb80ce5ec/lib/index.js#L40-L51). but a version that handles errors is more like [30 lines](https://github.com/dwyl/hapi-auth-github/blob/7989eb5db77ea7058a180a251a55b53b75607424/lib/http_request.js#L16)
+ use `request` node module to perform your requests: https://github.com/request/request (*the* ***most popular*** *way but has* ***many dependencies***...)
+ use `wreck` node module to perform your requests: https://github.com/hapijs/wreck (*less popular but* ***much cleaner*** *and only* ***two dependencies*** *both of which are very well written/maintained*)

If you're trying to keep things lightweight, node's `https` are good, but if you want something a bit more full-featured go with `wreck`.

If you need any help getting started, let me know. Hope the weekend is going well. :wink:

**Comment by sohilpandya** [comment]
Thanks @nelsonic! we used request for the weekend as we are used to it, but will definitely look into wreck.
