### ISSUE TITLE
NPM Contributors

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-auth-facebook#6]
@hdrdavies + @des-des + @jackcarlisle 
I was not able to find any of you on NPM...
![unable-to-find-hdrdavies-on-npm](https://cloud.githubusercontent.com/assets/194400/11445998/90bc234e-9529-11e5-8492-099d98679915.png)

If you want to be contributors (*and add to your NPM "portfolio"*...) reply with your NPM username. :wink:

**Comment by jackcarlisle** [comment]
@nelsonic NPM username = jackcarlisle

**Comment by hdrdavies** [comment]
NPM username = hdrdavies

**Comment by hdrdavies** [comment]
What tool do you use for those boxes on screenshots?

**Comment by des-des** [comment]
@nelsonic hey im signed up: des-des

**Comment by nelsonic** [comment]
Collaborators added. :+1: 
![hapi-auth-facebook-colaborators](https://cloud.githubusercontent.com/assets/194400/11448058/0138318e-9549-11e5-81f0-0617800e642f.png)

Boxes on screenshots: http://paintbrush.sourceforge.net/ (*sadly, Mac Only*...)
http://alternativeto.net/software/paintbrush/?platform=linux
